# Generated by Django 5.0.1 on 2024-01-20 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('descitem', models.TextField()),
                ('desc', models.TextField()),
                ('image', models.ImageField(upload_to='uploads')),
            ],
        ),
        migrations.CreateModel(
            name='sub_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AttendifyEvents.category')),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=255)),
                ('vanue', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('image', models.ImageField(upload_to='uploads')),
                ('desc', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=20)),
                ('e_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AttendifyEvents.sub_category')),
            ],
        ),
    ]
