# Generated by Django 5.0.1 on 2024-01-24 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AttendifyEvents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_category',
            name='main_category',
        ),
        migrations.DeleteModel(
            name='event',
        ),
        migrations.DeleteModel(
            name='sub_category',
        ),
    ]
