# Generated by Django 5.0.1 on 2024-01-24 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AttendifyEvents', '0002_remove_sub_category_main_category_delete_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AttendifyEvents.category')),
            ],
        ),
    ]
