# Generated by Django 5.0.1 on 2024-01-26 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AttendifyEvents', '0003_sub_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sub_category',
        ),
    ]
