# Generated by Django 5.0.1 on 2024-01-26 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AttendifyEvents', '0004_delete_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='uploade')),
                ('caption', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=10, max_digits=10)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total_seat', models.PositiveIntegerField()),
                ('available_seat', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('term_conditions', models.TextField()),
                ('company_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AttendifyEvents.category')),
            ],
        ),
    ]
