# Generated by Django 5.0.1 on 2024-01-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AttendifyEvents', '0005_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='available_seat',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='event',
            name='total_seat',
            field=models.CharField(max_length=1000),
        ),
    ]
