# Generated by Django 5.0.1 on 2024-01-29 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AttendifyEvents', '0008_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AttendifyEvents.sub_category'),
        ),
    ]
