# Generated by Django 5.0.1 on 2024-03-11 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AttendifyEvents', '0009_alter_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
