# Generated by Django 5.0.1 on 2024-03-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AttendifyEvents', '0010_event_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_category',
            name='image',
            field=models.ImageField(default=1, upload_to='uploads'),
            preserve_default=False,
        ),
    ]
