# Generated by Django 5.0.1 on 2024-03-11 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AttendifyEvents', '0011_sub_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Category',
            new_name='sub_category',
        ),
    ]
