# Generated by Django 5.0.1 on 2024-03-11 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AttendifyEvents', '0012_rename_category_event_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='quantity',
        ),
    ]
