# Generated by Django 5.0.3 on 2024-03-20 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AttendifyEvents', '0014_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='total_seat',
            new_name='total_seats',
        ),
    ]
