# Generated by Django 5.0.3 on 2024-03-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AttendifyEvents', '0015_rename_total_seat_event_total_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='available_seat',
            field=models.IntegerField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='event',
            name='total_seats',
            field=models.IntegerField(max_length=1000),
        ),
    ]
