# Generated by Django 4.2.6 on 2024-03-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AttendifyEvents', '0017_alter_event_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='available_seat',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='total_seats',
            field=models.IntegerField(),
        ),
    ]
