# Generated by Django 4.2.6 on 2024-03-22 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AttendifyEvents', '0018_alter_event_available_seat_alter_event_total_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
